#ifndef NEOOS_FONT_TERM_H
#define NEOOS_FONT_TERM_H
/* GENERATED by tools/bdf2c.py from
   third_party/spleen/spleen-12x24.bdf -- do not edit.
   Regenerate with `make font-regen`. */
#define TERM_GLYPH_W 12
#define TERM_GLYPH_H 24
extern const unsigned char term_glyphs[256][TERM_GLYPH_H * 2];
#endif
