#!/usr/bin/env python3
"""BDF bitmap font -> packed C glyph table. Standard library only.

Emits `const unsigned char NAME[256][cell_h*2]`. Row y of glyph c is
bytes [y*2 : y*2+2], MSB-first: byte 0 = columns 0..7 (MSB = column 0),
byte 1 = columns 8..(cell_w-1) in its high bits. Same convention as
kernel/dev/font8x16.c.

Codepoints the BDF does not define are left all-zero (blank).
Deterministic: same BDF in, byte-identical output.
"""
import argparse
import sys


def parse_bdf(f, cell_w, cell_h):
    """Return a list of 256 bytearray(cell_h*2)."""
    glyphs = [bytearray(cell_h * 2) for _ in range(256)]
    fbb = (cell_w, cell_h, 0, 0)   # FONTBOUNDINGBOX: w h xoff yoff
    enc = None
    bbx = None
    rows = []
    in_bitmap = False

    for line in f:
        parts = line.split()
        if not parts:
            continue
        kw = parts[0]

        if kw == "FONTBOUNDINGBOX":
            fbb = tuple(int(x) for x in parts[1:5])
        elif kw == "STARTCHAR":
            enc, bbx, rows = None, None, []
        elif kw == "ENCODING":
            enc = int(parts[1])
        elif kw == "BBX":
            bbx = tuple(int(x) for x in parts[1:5])   # w h xoff yoff
        elif kw == "BITMAP":
            in_bitmap = True
            rows = []
        elif kw == "ENDCHAR":
            in_bitmap = False
            if enc is not None and 0 <= enc < 256 and bbx is not None:
                _place(glyphs[enc], rows, bbx, fbb, cell_w, cell_h)
        elif in_bitmap:
            rows.append(kw)

    return glyphs


def _place(dst, hexrows, bbx, fbb, cell_w, cell_h):
    """Blit one glyph's BITMAP rows into the cell, honouring BBX and
    FONTBOUNDINGBOX offsets. BDF y grows upward from the baseline; the
    cell top is `fbb_h + fbb_yoff` pixels above the baseline."""
    bw, bh, bxo, byo = bbx
    _fw, fh, fxo, fyo = fbb
    top = (fh + fyo) - (bh + byo)     # screen row (down) of BITMAP row 0
    left = bxo - fxo                  # screen column of bit 0
    hexbits = ((bw + 7) // 8) * 8     # BDF pads each row up to a byte

    for i, hr in enumerate(hexrows):
        y = top + i
        if not (0 <= y < cell_h):
            continue
        val = int(hr, 16)
        for x in range(bw):
            if val & (1 << (hexbits - 1 - x)):
                cx = left + x
                if 0 <= cx < cell_w:
                    dst[y * 2 + (cx >> 3)] |= 0x80 >> (cx & 7)


def pixel(glyph, x, y):
    return bool(glyph[y * 2 + (x >> 3)] & (0x80 >> (x & 7)))


def emit_header(f, array, cell_w, cell_h, guard="NEOOS_FONT_TERM_H"):
    f.write(
        f"#ifndef {guard}\n"
        f"#define {guard}\n"
        f"/* GENERATED by tools/bdf2c.py from\n"
        f"   third_party/spleen/spleen-12x24.bdf -- do not edit.\n"
        f"   Regenerate with `make font-regen`. */\n"
        f"#define TERM_GLYPH_W {cell_w}\n"
        f"#define TERM_GLYPH_H {cell_h}\n"
        f"extern const unsigned char {array}[256][TERM_GLYPH_H * 2];\n"
        f"#endif\n"
    )


def emit_source(f, glyphs, array, found=None):
    f.write("/* GENERATED by tools/bdf2c.py -- do not edit. */\n")
    if found is not None:
        f.write(f"/* {found} glyphs from BDF, {256 - found} blank-filled. */\n")
    f.write('#include "font_term.h"\n\n')
    f.write(f"const unsigned char {array}[256][TERM_GLYPH_H * 2] = {{\n")
    for c, g in enumerate(glyphs):
        body = ",".join(f"0x{b:02x}" for b in g)
        f.write(f"    {{ {body} }}, /* 0x{c:02x} */\n")
    f.write("};\n")


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("bdf")
    ap.add_argument("--array", default="term_glyphs")
    ap.add_argument("--header", required=True)
    ap.add_argument("--source", required=True)
    ap.add_argument("--cell", default="12x24")
    a = ap.parse_args(argv)

    cw, ch = (int(x) for x in a.cell.split("x"))
    with open(a.bdf, encoding="latin-1") as f:
        glyphs = parse_bdf(f, cw, ch)
    found = sum(1 for g in glyphs if any(g))

    with open(a.header, "w") as f:
        emit_header(f, a.array, cw, ch)
    with open(a.source, "w") as f:
        emit_source(f, glyphs, a.array, found)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
